/**
 * Каталог плитки - Современная реализация (modal integrated)
 */

class TileCatalog {
    constructor() {
        this.config = { csvUrl: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRfhgka5nFoR1TXYDGQ5CziYYqGSDXjhw_yJeO-MqFTb-k_RWlkjvaWxy9vBzLuKmo4KdCnz2SAdvMh/pub?gid=0&single=true&output=csv', themes:{light:'light',dark:'dark'} };
        this.state = { products:[], filteredProducts:[], filters:{search:'',brands:new Set(),colors:new Set(),priceMin:0,priceMax:10000}, sort:'price-asc', theme:this.getStoredTheme(), loading:true, viewMode:2 };
        this.elements = {};
        this.init();
    }
    async init(){ this.initElements(); this.initTheme(); this.initEventListeners(); await this.loadData(); this.initFilters(); this.loadStoredViewMode(); this.updateViewButtons(); this.updateGridClass(); this.renderProducts(); this.hideLoadingScreen(); const isOpen=this.elements.filtersToggle?.checked||false; this.syncFiltersPlacement(isOpen);} 
    initElements(){ const sel={loadingScreen:'#loading-screen',themeToggle:'#theme-toggle',themeIcon:'.theme-icon',searchInput:'#search-input',brandFilters:'#brand-filters',colorFilters:'#color-filters',priceRange:'#price-range',priceMin:'#price-min',priceMax:'#price-max',clearFilters:'#clear-filters',sortSelect:'#sort-select',resultsCount:'#results-count',productsGrid:'#products-grid',noResults:'#no-results',filtersSidebar:'#filters-sidebar',filtersToggle:'#filters-toggle',filtersCollapsible:'#filters-collapsible',viewGrid1:'#view-grid-1',viewGrid2:'#view-grid-2'}; for (const[k,s] of Object.entries(sel)){ this.elements[k]=document.querySelector(s);} }
    initTheme(){ this.applyTheme(this.state.theme);} 
    applyTheme(t){ document.documentElement.setAttribute('data-theme',t); localStorage.setItem('theme',t); if(this.elements.themeIcon){ this.elements.themeIcon.textContent=t==='dark'?'☀️':'🌙'; } this.state.theme=t; }
    toggleTheme(){ this.applyTheme(this.state.theme==='dark'?'light':'dark'); }
    getStoredTheme(){ const s=localStorage.getItem('theme'); const sys=window.matchMedia('(prefers-color-scheme: dark)').matches; return s||(sys?'dark':'light'); }

    initEventListeners(){
        this.elements.themeToggle?.addEventListener('click',()=>this.toggleTheme());
        this.elements.searchInput?.addEventListener('input',e=>{ this.state.filters.search=e.target.value.toLowerCase().trim(); this.filterAndRenderProducts(); });
        this.elements.priceRange?.addEventListener('input',e=>{ const v=parseInt(e.target.value); this.state.filters.priceMax=v; if(this.elements.priceMax) this.elements.priceMax.value=v; this.updatePriceDisplay(); this.filterAndRenderProducts();});
        this.elements.priceMin?.addEventListener('input',e=>{ const v=parseInt(e.target.value)||0; const m=this.state.filters.priceMax; this.state.filters.priceMin=Math.min(v,m-1); e.target.value=this.state.filters.priceMin; this.filterAndRenderProducts();});
        this.elements.priceMax?.addEventListener('input',e=>{ const v=parseInt(e.target.value)||0; const min=this.state.filters.priceMin; const smax=parseInt(this.elements.priceRange?.max)||10000; this.state.filters.priceMax=Math.max(Math.min(v,smax),min+1); e.target.value=this.state.filters.priceMax; if(this.elements.priceRange) this.elements.priceRange.value=this.state.filters.priceMax; this.filterAndRenderProducts();});
        this.elements.sortSelect?.addEventListener('change',e=>{ this.state.sort=e.target.value; this.renderProducts();});
        this.elements.clearFilters?.addEventListener('click',()=>this.clearAllFilters());
        this.elements.viewGrid1?.addEventListener('click',()=>this.changeViewMode(1));
        this.elements.viewGrid2?.addEventListener('click',()=>this.changeViewMode(2));
        this.elements.filtersToggle?.addEventListener('change',e=>{ const o=e.target.checked; this.elements.filtersToggle.setAttribute('aria-expanded',String(o)); this.syncFiltersPlacement(o);});
        let t; window.addEventListener('resize',()=>{ clearTimeout(t); t=setTimeout(()=>{ const o=this.elements.filtersToggle?.checked||false; this.syncFiltersPlacement(o); },120);});

        // Delegation: open modal on card click
        this.elements.productsGrid?.addEventListener('click',(e)=>{
            const card=e.target.closest('.product-card'); if(!card) return;
            const id=card.dataset.id;
            const p=this.state.filteredProducts.find(x=>x.id===id)||this.state.products.find(x=>x.id===id);
            if(p) this.openProductModal(p);
        });
    }

    changeViewMode(c){ const n=Number(c)===1?1:2; this.state.viewMode=n; this.updateViewButtons(); this.updateGridClass(); localStorage.setItem('viewMode',String(n)); }
    syncFiltersPlacement(isOpen){ const s=this.elements.filtersSidebar,c=this.elements.filtersCollapsible; if(!s||!c) return; const m=window.innerWidth<=768; const panel=s.querySelector('.filters-panel')||c.querySelector('.filters-panel'); if(!panel) return; if(m){ if(!c.contains(panel)) c.appendChild(panel); c.classList.toggle('open',isOpen); if(isOpen) c.scrollIntoView({behavior:'smooth',block:'start'});} else { if(!s.contains(panel)) s.appendChild(panel); c.classList.remove('open'); c.style.removeProperty('display'); if(this.elements.filtersToggle){ this.elements.filtersToggle.checked=false; this.elements.filtersToggle.setAttribute('aria-expanded','false'); } } }
    updateViewButtons(){ document.querySelectorAll('.view-btn').forEach(b=>{ b.classList.remove('active'); b.setAttribute('aria-pressed','false');}); const byData=document.querySelector(`[data-columns="${this.state.viewMode}"]`); if(byData){ byData.classList.add('active'); byData.setAttribute('aria-pressed','true'); } const {viewGrid1,viewGrid2}=this.elements; if(viewGrid1){ viewGrid1.classList.toggle('active',this.state.viewMode===1); viewGrid1.setAttribute('aria-pressed',String(this.state.viewMode===1)); } if(viewGrid2){ viewGrid2.classList.toggle('active',this.state.viewMode===2); viewGrid2.setAttribute('aria-pressed',String(this.state.viewMode===2)); } }
    updateGridClass(){ if(!this.elements.productsGrid) return; this.elements.productsGrid.classList.remove('grid-1','grid-2'); this.elements.productsGrid.classList.add(`grid-${this.state.viewMode}`); }
    loadStoredViewMode(){ const s=localStorage.getItem('viewMode'); if(s&&['1','2'].includes(s)){ this.state.viewMode=parseInt(s);} else { localStorage.setItem('viewMode',String(this.state.viewMode)); } }
    updatePriceDisplay(){ if(this.elements.priceMin&&this.elements.priceMax){ this.log(`💰 Диапазон цен: ${this.state.filters.priceMin} - ${this.state.filters.priceMax}`);} }

    async loadData(){ try{ await this.loadFromGoogleSheets(); }catch(err){ this.log('❌ Ошибка загрузки из Google Sheets:',err?.message); this.loadDemoData(); } }
    async loadFromGoogleSheets(){ const url=`${this.config.csvUrl}&_cachebust=${Date.now()}`; const r=await fetch(url,{method:'GET',headers:{'Accept':'text/csv,application/csv,text/plain','Cache-Control':'no-cache'},cache:'no-store'}); if(!r.ok) throw new Error(`HTTP ${r.status}: ${r.statusText}`); const csv=await r.text(); if(csv.length<50) throw new Error('Слишком короткий ответ от сервера'); this.parseCSVData(csv); }
    parseCSVData(csv){ try{ const wb=XLSX.read(csv,{type:'string'}); const ws=wb.Sheets[wb.SheetNames[0]]; const rows=XLSX.utils.sheet_to_json(ws,{header:1}); if(rows.length<2) throw new Error('Недостаточно данных в CSV'); this.state.products=rows.slice(1).filter(r=>r&&r.length>0).map(r=>({ id:this.generateId(), name:this.cleanString(this.getString(r[0]))||'Без названия', brand:this.cleanString(this.getString(r[1]))||'Неизвестно', color:this.cleanString(this.getString(r[2]))||'Не указан', price:this.getNumber(r[3])||0, description:this.cleanString(this.getString(r[4]))||'', image:this.getString(r[5])||'', inStock:this.getBoolean(r[6]), onDemand:this.getBoolean(r[7]), hidden:this.getBoolean(r[8]) })).filter(p=>{ const ok=(p.inStock||p.onDemand)&&!p.hidden; return ok&&p.name!=='Без названия'; }); }catch(e){ this.log('❌ Ошибка парсинга CSV:',e); this.loadDemoData(); } }

    cleanString(s){ if(!s) return ''; return String(s).replace(/['\"<>]/g,'').replace(/\s+/g,' ').trim(); }
    loadDemoData(){ this.state.products=[{id:'demo-1',name:'Керамическая плитка Marmo',brand:'Ceramica',color:'Белый',price:1250,description:'Элегантная керамическая плитка с мраморным узором. Идеально подходит для ванной комнаты и кухни.',image:'',inStock:true,onDemand:false,hidden:false},{id:'demo-2',name:'Плитка Modern Pattern',brand:'ContempoStyle',color:'Серый',price:890,description:'Современная плитка с геометрическим рисунком.',image:'',inStock:true,onDemand:false,hidden:false},{id:'demo-3',name:'Мозаика Vintage',brand:'Retro Style',color:'Бежевый',price:1890,description:'Винтажная мозаика для создания уютной и теплой атмосферы в доме.',image:'',inStock:false,onDemand:true,hidden:false},{id:'demo-4',name:'Плитка Wood Look',brand:'Natural',color:'Коричневый',price:1450,description:'Керамическая плитка под дерево. Натуральный вид без недостатков дерева.',image:'',inStock:true,onDemand:false,hidden:false},{id:'demo-5',name:'Глянцевая плитка Metro',brand:'Classic',color:'Черный',price:750,description:'Классическая глянцевая плитка в стиле метро. Универсальное решение для любого интерьера.',image:'',inStock:true,onDemand:false,hidden:false}]; }

    initFilters(){ const brands=[...new Set(this.state.products.map(p=>p.brand))].sort(); const colors=[...new Set(this.state.products.map(p=>p.color))].sort(); if(this.elements.brandFilters){ this.elements.brandFilters.innerHTML=brands.map(b=>this.createCheckboxFilter('brand',b)).join(''); this.elements.brandFilters.addEventListener('change',e=>{ if(e.target.type==='checkbox'){ if(e.target.checked) this.state.filters.brands.add(e.target.value); else this.state.filters.brands.delete(e.target.value); this.filterAndRenderProducts(); }});} if(this.elements.colorFilters){ this.elements.colorFilters.innerHTML=colors.map(c=>this.createCheckboxFilter('color',c)).join(''); this.elements.colorFilters.addEventListener('change',e=>{ if(e.target.type==='checkbox'){ if(e.target.checked) this.state.filters.colors.add(e.target.value); else this.state.filters.colors.delete(e.target.value); this.filterAndRenderProducts(); }});} const prices=this.state.products.map(p=>p.price).filter(Number.isFinite); const max=prices.length?Math.max(...prices):0; this.state.filters.priceMax=max; if(this.elements.priceRange){ this.elements.priceRange.max=String(max); this.elements.priceRange.value=String(max);} if(this.elements.priceMax){ this.elements.priceMax.value=String(max);} }
    createCheckboxFilter(t,v){ const id=`${t}-${v.replace(/\s+/g,'-').toLowerCase()}`; return `<div class="checkbox-item"><input type="checkbox" id="${id}" value="${v}"><label for="${id}" class="checkbox-text">${v}</label></div>`; }

    filterAndRenderProducts(){ this.applyFilters(); this.renderProducts(); }
    applyFilters(){ this.state.filteredProducts=this.state.products.filter(p=>{ if(this.state.filters.search){ const s=(p.name+' '+p.brand+' '+p.color+' '+p.description).toLowerCase(); if(!s.includes(this.state.filters.search)) return false; } if(this.state.filters.brands.size>0&&!this.state.filters.brands.has(p.brand)) return false; if(this.state.filters.colors.size>0&&!this.state.filters.colors.has(p.color)) return false; if(p.price<this.state.filters.priceMin||p.price>this.state.filters.priceMax) return false; return true; }); }

    renderProducts(){ if(!this.elements.productsGrid) return; this.applyFilters(); this.sortProducts(); this.updateResultsCount(); if(this.state.filteredProducts.length===0){ this.showNoResults(); } else { this.hideNoResults(); this.elements.productsGrid.innerHTML=this.state.filteredProducts.map(p=>this.createProductCard(p)).join(''); } }
    sortProducts(){ this.state.filteredProducts.sort((a,b)=>{ switch(this.state.sort){ case 'price-asc': return a.price-b.price; case 'price-desc': return b.price-a.price; case 'name-asc': return a.name.localeCompare(b.name,'ru'); case 'name-desc': return b.name.localeCompare(a.name,'ru'); default: return 0; } }); }

    createProductCard(p){ const badges=[]; if(p.inStock) badges.push('<span class="badge badge-success">В наличии</span>'); if(p.onDemand) badges.push('<span class="badge badge-warning">Под заказ</span>'); const img=p.image&&p.image.trim()?`<img src="${p.image}" alt="${p.name}" loading="lazy" onerror="this.style.display='none'; this.parentNode.querySelector('.product-placeholder').style.display='flex';">`:''; const price=p.price>0?p.price.toLocaleString('ru-RU')+' ₽':'По запросу'; return `<article class="product-card" data-id="${p.id}"><div class="product-image">${img}<div class="product-placeholder" style="${p.image?'display: none;':'display: flex;'}">🏠</div>${badges.length>0?`<div class="product-status">${badges[0].replace('<span class=\"badge badge-success\">','').replace('<span class=\"badge badge-warning\">','').replace('</span>','')}</div>`:''}</div><div class="product-content"><div class="product-header"><h3 class="product-title">${p.name}</h3><div class="product-price">${price}</div></div><div class="product-meta"><span class="product-brand"><strong>Бренд:</strong> ${p.brand}</span><span class="product-color"><strong>Цвет:</strong> ${p.color}</span></div>${p.description?`<p class="product-description">${p.description}</p>`:''}<div class="product-badges">${badges.join('')}</div><a href="https://vk.com/plitochik44" target="_blank" class="product-contact">Связаться</a></div></article>`; }

    updateResultsCount(){ if(this.elements.resultsCount){ const total=this.state.products.length; const filtered=this.state.filteredProducts.length; this.elements.resultsCount.textContent=`Найдено товаров: ${filtered} из ${total}`; } }
    showNoResults(){ this.elements.noResults?.classList.remove('hidden'); if(this.elements.productsGrid) this.elements.productsGrid.innerHTML=''; }
    hideNoResults(){ this.elements.noResults?.classList.add('hidden'); }
    clearAllFilters(){ this.state.filters.search=''; if(this.elements.searchInput) this.elements.searchInput.value=''; this.state.filters.brands.clear(); this.elements.brandFilters?.querySelectorAll('input[type="checkbox"]').forEach(cb=>cb.checked=false); this.state.filters.colors.clear(); this.elements.colorFilters?.querySelectorAll('input[type="checkbox"]').forEach(cb=>cb.checked=false); const prices=this.state.products.map(p=>p.price).filter(Number.isFinite); const max=prices.length?Math.max(...prices):0; this.state.filters.priceMin=0; this.state.filters.priceMax=max; if(this.elements.priceMin) this.elements.priceMin.value='0'; if(this.elements.priceMax) this.elements.priceMax.value=String(max); if(this.elements.priceRange){ this.elements.priceRange.value=String(max); this.elements.priceRange.max=String(max);} this.filterAndRenderProducts(); }
    hideLoadingScreen(){ if(this.elements.loadingScreen){ this.elements.loadingScreen.style.opacity='0'; setTimeout(()=>{ this.elements.loadingScreen.style.display='none'; },300);} }
    handleError(msg,err){ this.log('❌',msg,err); this.hideLoadingScreen(); this.notify('Произошла ошибка. Показаны демо-данные.'); }
    getString(v){ return v?String(v).trim():''; }
    getNumber(v){ const n=parseFloat(v); return isNaN(n)?0:n; }
    getBoolean(v){ if(typeof v==='boolean') return v; if(typeof v==='string'){ const l=v.toLowerCase().trim(); return l==='true'||l==='1'||l==='да'||l==='yes'; } return Boolean(v); }
    generateId(){ return 'product-'+Math.random().toString(36).slice(2,11); }
    notify(m){ try{ if(!m) return; const n=document.createElement('div'); n.className='toast-note'; n.textContent=m; Object.assign(n.style,{position:'fixed',bottom:'16px',left:'50%',transform:'translateX(-50%)',background:'rgba(0,0,0,.8)',color:'#fff',padding:'10px 14px',borderRadius:'8px',fontSize:'14px',zIndex:99999,boxShadow:'0 4px 16px rgba(0,0,0,.25)'}); document.body.appendChild(n); setTimeout(()=>n.remove(),3500);}catch(_){}}
    log(...a){ console.log('[TileCatalog]',...a); }

    // ===== Modal logic =====
    openProductModal(p){ const modal=document.getElementById('product-modal'); if(!modal) return; const img=document.getElementById('modal-image'); const ph=document.getElementById('modal-image-ph'); const title=document.getElementById('modal-title'); const price=document.getElementById('modal-price'); const badges=document.getElementById('modal-badges'); const brand=document.getElementById('modal-brand'); const color=document.getElementById('modal-color'); const status=document.getElementById('modal-status'); const desc=document.getElementById('modal-desc'); title.textContent=p.name; price.textContent=p.price>0?p.price.toLocaleString('ru-RU')+' ₽':'По запросу'; brand.textContent=p.brand; color.textContent=p.color; status.textContent=p.inStock?'В наличии':(p.onDemand?'Под заказ':'Недоступно'); desc.textContent=p.description||''; badges.innerHTML=''; if(p.inStock) badges.insertAdjacentHTML('beforeend','<span class="badge badge-success">В наличии</span>'); if(p.onDemand) badges.insertAdjacentHTML('beforeend','<span class="badge badge-warning">Под заказ</span>'); if(p.image&&p.image.trim()){ img.src=p.image; img.alt=p.name; img.style.display='block'; ph.style.display='none'; img.onerror=()=>{ img.style.display='none'; ph.style.display='grid'; }; } else { img.removeAttribute('src'); img.style.display='none'; ph.style.display='grid'; }
      modal.classList.add('open'); document.documentElement.style.overflow='hidden'; this._trapFocusOpen(modal);
      const onBackdrop=(e)=>{ if(e.target===modal||e.target.classList.contains('modal__backdrop')) this.closeProductModal(); };
      const onEsc=(e)=>{ if(e.key==='Escape') this.closeProductModal(); };
      modal.addEventListener('click',onBackdrop,{ once:true }); document.addEventListener('keydown',onEsc,{ once:true });
      modal.querySelector('.modal__close')?.addEventListener('click',()=>this.closeProductModal(),{ once:true });
      document.getElementById('modal-close-btn')?.addEventListener('click',()=>this.closeProductModal(),{ once:true });
    }
    closeProductModal(){ const modal=document.getElementById('product-modal'); if(!modal) return; modal.classList.remove('open'); document.documentElement.style.overflow=''; this._trapFocusClose(); }
    _trapFocusOpen(c){ const f=c.querySelectorAll('a[href], button, textarea, input, select, [tabindex]:not([tabindex="-1"])'); this._focusElems=Array.from(f); this._focusIndex=0; this._lastActive=document.activeElement; (this._focusElems[0]||c).focus(); this._onFocusKey=(e)=>{ if(e.key!=='Tab') return; e.preventDefault(); this._focusIndex=(this._focusIndex+(e.shiftKey?-1:1)+this._focusElems.length)%this._focusElems.length; this._focusElems[this._focusIndex].focus(); }; c.addEventListener('keydown',this._onFocusKey); }
    _trapFocusClose(){ const c=document.getElementById('product-modal'); if(this._onFocusKey) c?.removeEventListener('keydown',this._onFocusKey); this._lastActive?.focus?.(); this._onFocusKey=null; this._focusElems=null; }
}

window.TileCatalog = TileCatalog;
